name: Integrations

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache pnpm
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
        AUTH_GOOGLE_ID: ${{secrets.AUTH-GOOGLE_ID}}
        AUTH_GOOGLE_SECRET: ${{secrets.AUTH-GOOGLE_SECRET}}
        AUTH_SECRET: ${{secrets.AUTH_SECRET}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
        GEMINI_API_KEY_MAIN: ${{secrets.GEMINI_API_KEY_MAIN}}
        NEXT_BASE_URL: ${{secrets.NEXT_BASE_URL}}
        SMTP_HOST: ${{secrets.SMTP_HOST}}
        SMTP_PORT: ${{secrets.SMTP_PORT}}
        SMTP_USER: ${{secrets.SMTP_USER}}
        SMTP_PASS: ${{secrets.SMTP_PASS}}
        NEXT_PUBLIC_POSTHOG_KEY: ${{secrets.NEXT_PUBLIC_POSTHOG_KEY}}
        NEXT_PUBLIC_POSTHOG_HOST: ${{secrets.NEXT_PUBLIC_POSTHOG_HOST}}
        RAZORPAY_KEY_ID: ${{secrets.RAZORPAY_KEY_ID}}
        RAZORPAY_KEY_SECRET: ${{secrets.RAZORPAY_KEY_SECRET}}
        RAZORPAY_WEBHOOK_SECRET: ${{secrets.RAZORPAY_WEBHOOK_SECRET}}
        NEXT_PUBLIC_RAZORPAY_KEY_ID: ${{secrets.AUTH-GOOGLE_ID.NEXT_PUBLIC_RAZORPAY_KEY_ID}}
